name: Java CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven build
        run: mvn -B clean verify

      - name: Upload test reports (if failure)
        if: failure()
        uses: actions/upload-artifacts@v4
        with:
          name: test-reports
          path: target/surefire-reports/


